import {
  ArrowRight,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  FileCheck2,
  GitBranch,
  Workflow,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"

function FlowArrow() {
  return (
    <div className="flex items-center justify-center text-stone-400">
      <ArrowRight className="size-6" />
    </div>
  )
}

function FlowCard({
  title,
  items,
  accent = "stone",
}: {
  title: string
  items: string[]
  accent?: "stone" | "amber" | "violet"
}) {
  const accentClass =
    accent === "amber"
      ? "border-amber-200 bg-amber-50 text-amber-800"
      : accent === "violet"
        ? "border-violet-200 bg-violet-50 text-violet-800"
        : "border-stone-200 bg-white text-stone-800"

  return (
    <div className={`rounded-lg border p-4 shadow-sm ${accentClass}`}>
      <p className="text-sm font-semibold">{title}</p>
      <div className="mt-3 space-y-2">
        {items.map((item) => (
          <div
            key={item}
            className="rounded-md border border-white/70 bg-white/75 px-3 py-2 text-sm text-stone-700"
          >
            {item}
          </div>
        ))}
      </div>
    </div>
  )
}

function ApprovalDiamond({ title }: { title: string }) {
  return (
    <div className="flex flex-col items-center gap-3">
      <div className="flex size-28 rotate-45 items-center justify-center border border-amber-300 bg-white shadow-sm">
        <span className="-rotate-45 text-center text-sm font-semibold leading-5 text-stone-800">
          {title}
        </span>
      </div>
      <div className="space-y-2 text-sm text-stone-600">
        <p className="flex items-start gap-2">
          <CheckCircle2 className="mt-0.5 size-4 text-amber-700" />
          Approve by responsible managers
        </p>
      </div>
    </div>
  )
}

function SignatureRow() {
  const roles = [
    "PD-ECR initiator manager",
    "Initiator HoD",
    "Business / Product owner",
  ]

  return (
    <div className="grid gap-3 rounded-lg border border-stone-200 bg-stone-50 p-4 md:grid-cols-[1fr_1fr_1fr_14rem]">
      {roles.map((role) => (
        <div key={role} className="rounded-md bg-white p-3">
          <p className="text-sm font-semibold text-stone-800">{role}</p>
          <p className="mt-4 border-t border-dashed border-stone-300 pt-2 text-xs text-stone-500">
            Signature
          </p>
        </div>
      ))}
      <div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm font-medium text-amber-900">
        Based on CASE, add manager approval when needed.
      </div>
    </div>
  )
}

function ProcessFlowChart() {
  return (
    <div className="space-y-6">
      <div className="overflow-x-auto rounded-xl border border-stone-200 bg-stone-50 p-4">
        <div className="min-w-[1180px]">
          <div className="grid grid-cols-[120px_36px_260px_36px_120px_36px_260px_36px_120px_36px_170px] items-center">
            <div className="rounded-full bg-violet-700 px-5 py-3 text-center text-sm font-semibold text-white shadow-sm">
              Main UI
            </div>
            <FlowArrow />
            <div>
              <FlowCard
                title="Content generated by AI"
                items={[
                  "Change request description",
                  "Impact analysis",
                  "Validation &trial run plan",
                  "Trial run solution / EPQ / QA check",
                ]}
                accent="amber"
              />
              <div className="mt-3 rounded-lg border border-stone-200 bg-white p-3 text-sm text-stone-600">
                Engineer fills content; responsible manager confirms.
              </div>
            </div>
            <FlowArrow />
            <ApprovalDiamond title="1st approval" />
            <FlowArrow />
            <FlowCard
              title="Approved execution package"
              items={[
                "Validation &trial run plan result",
                "Implementation task plan",
              ]}
            />
            <FlowArrow />
            <ApprovalDiamond title="2nd approval" />
            <FlowArrow />
            <FlowCard
              title="Closure"
              items={["Implementation result", "Close"]}
              accent="violet"
            />
          </div>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="rounded-lg border border-stone-200 bg-white p-4">
          <ClipboardList className="size-5 text-amber-700" />
          <p className="mt-2 text-sm font-semibold text-stone-800">
            1. Prepare
          </p>
          <p className="mt-1 text-sm leading-6 text-stone-600">
            Generate four report modules and align validation inputs.
          </p>
        </div>
        <div className="rounded-lg border border-stone-200 bg-white p-4">
          <ClipboardCheck className="size-5 text-amber-700" />
          <p className="mt-2 text-sm font-semibold text-stone-800">
            2. Approve & validate
          </p>
          <p className="mt-1 text-sm leading-6 text-stone-600">
            Confirm validation plan, trial run result, and task plan.
          </p>
        </div>
        <div className="rounded-lg border border-stone-200 bg-white p-4">
          <FileCheck2 className="size-5 text-amber-700" />
          <p className="mt-2 text-sm font-semibold text-stone-800">
            3. Implement & close
          </p>
          <p className="mt-1 text-sm leading-6 text-stone-600">
            Approve introduction, record implementation result, then close.
          </p>
        </div>
      </div>

      <SignatureRow />
    </div>
  )
}

export function PdEcrProcessFlowButton({ className }: { className?: string }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className={className || "bg-white"}>
          <Workflow className="size-4" />
          Process flow
        </Button>
      </DialogTrigger>
      <DialogContent className="max-h-[90vh] overflow-y-auto bg-white text-stone-900 sm:max-w-7xl">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-lg bg-amber-50 text-amber-700">
              <GitBranch className="size-5" />
            </div>
            <div>
              <DialogTitle className="text-2xl">Process flow chart</DialogTitle>
              <DialogDescription>
                Static PD-ECR workflow overview for presentation and process
                alignment.
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>
        <ProcessFlowChart />
        <DialogFooter>
          <DialogClose asChild>
            <Button variant="outline">Close</Button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
