/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutPdEcrRouteImport } from './routes/_layout/pd-ecr'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'
import { Route as LayoutPdEcrNewRouteImport } from './routes/_layout/pd-ecr_.new'
import { Route as LayoutPdEcrContentRouteImport } from './routes/_layout/pd-ecr_.content'
import { Route as LayoutPdEcrCasesRouteImport } from './routes/_layout/pd-ecr_.cases'
import { Route as LayoutPdEcrContentModuleIdRouteImport } from './routes/_layout/pd-ecr_.content_.$moduleId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPdEcrRoute = LayoutPdEcrRouteImport.update({
  id: '/pd-ecr',
  path: '/pd-ecr',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutPdEcrNewRoute = LayoutPdEcrNewRouteImport.update({
  id: '/pd-ecr_/new',
  path: '/pd-ecr/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPdEcrContentRoute = LayoutPdEcrContentRouteImport.update({
  id: '/pd-ecr_/content',
  path: '/pd-ecr/content',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPdEcrCasesRoute = LayoutPdEcrCasesRouteImport.update({
  id: '/pd-ecr_/cases',
  path: '/pd-ecr/cases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPdEcrContentModuleIdRoute =
  LayoutPdEcrContentModuleIdRouteImport.update({
    id: '/pd-ecr_/content_/$moduleId',
    path: '/pd-ecr/content/$moduleId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/pd-ecr': typeof LayoutPdEcrRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/pd-ecr/cases': typeof LayoutPdEcrCasesRoute
  '/pd-ecr/content': typeof LayoutPdEcrContentRoute
  '/pd-ecr/new': typeof LayoutPdEcrNewRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/pd-ecr/content/$moduleId': typeof LayoutPdEcrContentModuleIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/pd-ecr': typeof LayoutPdEcrRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/pd-ecr/cases': typeof LayoutPdEcrCasesRoute
  '/pd-ecr/content': typeof LayoutPdEcrContentRoute
  '/pd-ecr/new': typeof LayoutPdEcrNewRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/pd-ecr/content/$moduleId': typeof LayoutPdEcrContentModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/pd-ecr': typeof LayoutPdEcrRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/pd-ecr_/cases': typeof LayoutPdEcrCasesRoute
  '/_layout/pd-ecr_/content': typeof LayoutPdEcrContentRoute
  '/_layout/pd-ecr_/new': typeof LayoutPdEcrNewRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/_layout/pd-ecr_/content_/$moduleId': typeof LayoutPdEcrContentModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/pd-ecr'
    | '/projects'
    | '/settings'
    | '/pd-ecr/cases'
    | '/pd-ecr/content'
    | '/pd-ecr/new'
    | '/projects/$projectId'
    | '/pd-ecr/content/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/pd-ecr'
    | '/projects'
    | '/settings'
    | '/'
    | '/pd-ecr/cases'
    | '/pd-ecr/content'
    | '/pd-ecr/new'
    | '/projects/$projectId'
    | '/pd-ecr/content/$moduleId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/pd-ecr'
    | '/_layout/projects'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/pd-ecr_/cases'
    | '/_layout/pd-ecr_/content'
    | '/_layout/pd-ecr_/new'
    | '/_layout/projects/$projectId'
    | '/_layout/pd-ecr_/content_/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pd-ecr': {
      id: '/_layout/pd-ecr'
      path: '/pd-ecr'
      fullPath: '/pd-ecr'
      preLoaderRoute: typeof LayoutPdEcrRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/pd-ecr_/new': {
      id: '/_layout/pd-ecr_/new'
      path: '/pd-ecr/new'
      fullPath: '/pd-ecr/new'
      preLoaderRoute: typeof LayoutPdEcrNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pd-ecr_/content': {
      id: '/_layout/pd-ecr_/content'
      path: '/pd-ecr/content'
      fullPath: '/pd-ecr/content'
      preLoaderRoute: typeof LayoutPdEcrContentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pd-ecr_/cases': {
      id: '/_layout/pd-ecr_/cases'
      path: '/pd-ecr/cases'
      fullPath: '/pd-ecr/cases'
      preLoaderRoute: typeof LayoutPdEcrCasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pd-ecr_/content_/$moduleId': {
      id: '/_layout/pd-ecr_/content_/$moduleId'
      path: '/pd-ecr/content/$moduleId'
      fullPath: '/pd-ecr/content/$moduleId'
      preLoaderRoute: typeof LayoutPdEcrContentModuleIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutProjectsRouteChildren {
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPdEcrRoute: typeof LayoutPdEcrRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPdEcrCasesRoute: typeof LayoutPdEcrCasesRoute
  LayoutPdEcrContentRoute: typeof LayoutPdEcrContentRoute
  LayoutPdEcrNewRoute: typeof LayoutPdEcrNewRoute
  LayoutPdEcrContentModuleIdRoute: typeof LayoutPdEcrContentModuleIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPdEcrRoute: LayoutPdEcrRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPdEcrCasesRoute: LayoutPdEcrCasesRoute,
  LayoutPdEcrContentRoute: LayoutPdEcrContentRoute,
  LayoutPdEcrNewRoute: LayoutPdEcrNewRoute,
  LayoutPdEcrContentModuleIdRoute: LayoutPdEcrContentModuleIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
