/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PdfUploadRouteImport } from './routes/pdf-upload'
import { Route as PdEcrModulesRouteImport } from './routes/pd-ecr-modules'
import { Route as PdEcrFormRouteImport } from './routes/pd-ecr-form'
import { Route as NozzleReportRouteImport } from './routes/nozzle-report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfUploadRoute = PdfUploadRouteImport.update({
  id: '/pdf-upload',
  path: '/pdf-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PdEcrModulesRoute = PdEcrModulesRouteImport.update({
  id: '/pd-ecr-modules',
  path: '/pd-ecr-modules',
  getParentRoute: () => rootRouteImport,
} as any)
const PdEcrFormRoute = PdEcrFormRouteImport.update({
  id: '/pd-ecr-form',
  path: '/pd-ecr-form',
  getParentRoute: () => rootRouteImport,
} as any)
const NozzleReportRoute = NozzleReportRouteImport.update({
  id: '/nozzle-report',
  path: '/nozzle-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nozzle-report': typeof NozzleReportRoute
  '/pd-ecr-form': typeof PdEcrFormRoute
  '/pd-ecr-modules': typeof PdEcrModulesRoute
  '/pdf-upload': typeof PdfUploadRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nozzle-report': typeof NozzleReportRoute
  '/pd-ecr-form': typeof PdEcrFormRoute
  '/pd-ecr-modules': typeof PdEcrModulesRoute
  '/pdf-upload': typeof PdfUploadRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/nozzle-report': typeof NozzleReportRoute
  '/pd-ecr-form': typeof PdEcrFormRoute
  '/pd-ecr-modules': typeof PdEcrModulesRoute
  '/pdf-upload': typeof PdfUploadRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nozzle-report'
    | '/pd-ecr-form'
    | '/pd-ecr-modules'
    | '/pdf-upload'
    | '/recover-password'
    | '/reports'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/nozzle-report'
    | '/pd-ecr-form'
    | '/pd-ecr-modules'
    | '/pdf-upload'
    | '/recover-password'
    | '/reports'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/nozzle-report'
    | '/pd-ecr-form'
    | '/pd-ecr-modules'
    | '/pdf-upload'
    | '/recover-password'
    | '/reports'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  NozzleReportRoute: typeof NozzleReportRoute
  PdEcrFormRoute: typeof PdEcrFormRoute
  PdEcrModulesRoute: typeof PdEcrModulesRoute
  PdfUploadRoute: typeof PdfUploadRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-upload': {
      id: '/pdf-upload'
      path: '/pdf-upload'
      fullPath: '/pdf-upload'
      preLoaderRoute: typeof PdfUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pd-ecr-modules': {
      id: '/pd-ecr-modules'
      path: '/pd-ecr-modules'
      fullPath: '/pd-ecr-modules'
      preLoaderRoute: typeof PdEcrModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pd-ecr-form': {
      id: '/pd-ecr-form'
      path: '/pd-ecr-form'
      fullPath: '/pd-ecr-form'
      preLoaderRoute: typeof PdEcrFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nozzle-report': {
      id: '/nozzle-report'
      path: '/nozzle-report'
      fullPath: '/nozzle-report'
      preLoaderRoute: typeof NozzleReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  NozzleReportRoute: NozzleReportRoute,
  PdEcrFormRoute: PdEcrFormRoute,
  PdEcrModulesRoute: PdEcrModulesRoute,
  PdfUploadRoute: PdfUploadRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
